export const COMPANY_BUSINESS_PAYMENT_TYPE_CASH_BEFORE_DELIVERY = {
  key: 'CASH_BEFORE_DELIVERY',
  label: '送貨前支付',
};
export const COMPANY_BUSINESS_PAYMENT_TYPE_CASH_ON_DELIVERY = {
  key: 'CASH_ON_DELIVERY',
  label: '送貨時支付',
};
export const COMPANY_BUSINESS_PAYMENT_TYPE_CASH_IN_ADVANCE = {
  key: 'CASH_IN_ADVANCE',
  label: '預付款',
};
export const COMPANY_BUSINESS_PAYMENT_TYPE_CASH_IN_ORDER = {
  key: 'CASH_IN_ORDER',
  label: '落訂單時支付',
};
export const COMPANY_BUSINESS_PAYMENT_TYPE_MONTHLY = {
  key: 'MONTHLY',
  label: '月結',
};

export const COMPANY_BUSINESS_PAYMENT_TYPES = [
  COMPANY_BUSINESS_PAYMENT_TYPE_CASH_BEFORE_DELIVERY,
  COMPANY_BUSINESS_PAYMENT_TYPE_CASH_ON_DELIVERY,
  COMPANY_BUSINESS_PAYMENT_TYPE_CASH_IN_ADVANCE,
  COMPANY_BUSINESS_PAYMENT_TYPE_CASH_IN_ORDER,
  COMPANY_BUSINESS_PAYMENT_TYPE_MONTHLY,
];
