export const ITEM_SPECIFICATION_STOCK_TYPE_LIMITED = { key: 'LIMITED', label: '有限' };
export const ITEM_SPECIFICATION_STOCK_TYPE_UNLIMITED = { key: 'UNLIMITED', label: '無限' };

export const ITEM_SPECIFICATION_STOCK_TYPES = [
  ITEM_SPECIFICATION_STOCK_TYPE_LIMITED,
  ITEM_SPECIFICATION_STOCK_TYPE_UNLIMITED,
];
