export const ORDER_STATUS_ORDER_RECEIVED = { key: 'ORDER_RECEIVED', label: '訂單被接收' };
export const ORDER_STATUS_ORDER_PENDING_APPROVAL = {
  key: 'ORDER_PENDING_APPROVAL',
  label: '訂單等待審批',
};
export const ORDER_STATUS_ORDER_PENDING = { key: 'ORDER_PENDING', label: '訂單處理中' };
export const ORDER_STATUS_ORDER_READY_TO_PICK_UP = {
  key: 'ORDER_READY_TO_PICK_UP',
  label: '訂單準備完成',
};
export const ORDER_STATUS_ORDER_FINISHED = { key: 'ORDER_RECEIVED', label: '訂單完成' };

export const ORDER_STATUSES = [
  ORDER_STATUS_ORDER_RECEIVED,
  ORDER_STATUS_ORDER_PENDING_APPROVAL,
  ORDER_STATUS_ORDER_PENDING,
  ORDER_STATUS_ORDER_READY_TO_PICK_UP,
  ORDER_STATUS_ORDER_FINISHED,
];
