export const PRINTER_FEIE_58MM_RECEIPT_PRINTER = {
  key: 'FEIE_58MM_RECEIPT_PRINTER',
  label: '飛鵝58MM 4G/多接口/WiFi无线打印機',
};
export const PRINTER_FEIE_80MM_RECEIPT_PRINTER = {
  key: 'FEIE_80MM_RECEIPT_PRINTER',
  label: '飛鵝80MM 4G/多接口/WiFi无线打印機',
};

export const PRINTERS = [PRINTER_FEIE_58MM_RECEIPT_PRINTER, PRINTER_FEIE_80MM_RECEIPT_PRINTER];
