export const SYSTEM_LOG_OPERATION_CREATE = { key: 'CREATE', label: '創建' };
export const SYSTEM_LOG_OPERATION_DELETE = { key: 'DELETE', label: '删除' };
export const SYSTEM_LOG_OPERATION_UPDATE = { key: 'UPDATE', label: '更新' };

export const SYSTEM_LOG_OPERATIONS = [
  SYSTEM_LOG_OPERATION_CREATE,
  SYSTEM_LOG_OPERATION_DELETE,
  SYSTEM_LOG_OPERATION_UPDATE,
];
